In [1]:
import pandas as pd

In [2]:
path="/content/drive/MyDrive/DATASET/Salaries.csv"

In [8]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [9]:
df = pd.read_csv(path)
df

<ipython-input-9-10c1b0b75bb4>:1: DtypeWarning: Columns (12) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(path)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
148645,148646,Carolyn A Wilson,Human Services Technician,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148646,148648,Joann Anderson,Communications Dispatcher 2,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148647,148649,Leon Walker,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148648,148650,Roy I Tillery,Custodian,0.00,0.00,0.00,0.0,0.00,0.00,2014,NaN,San Francisco,PT
148649,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.00,0.00,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [10]:
df.head(5)

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
0,1,NATHANIEL FORD,GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY,167411.18,0.00,400184.25,NaN,567595.43,567595.43,2011,NaN,San Francisco,NaN
1,2,GARY JIMENEZ,CAPTAIN III (POLICE DEPARTMENT),155966.02,245131.88,137811.38,NaN,538909.28,538909.28,2011,NaN,San Francisco,NaN
2,3,ALBERT PARDINI,CAPTAIN III (POLICE DEPARTMENT),212739.13,106088.18,16452.60,NaN,335279.91,335279.91,2011,NaN,San Francisco,NaN
3,4,CHRISTOPHER CHONG,WIRE ROPE CABLE MAINTENANCE MECHANIC,77916.00,56120.71,198306.90,NaN,332343.61,332343.61,2011,NaN,San Francisco,NaN
4,5,PATRICK GARDNER,"DEPUTY CHIEF OF DEPARTMENT,(FIRE DEPARTMENT)",134401.60,9737.00,182234.59,NaN,326373.19,326373.19,2011,NaN,San Francisco,NaN

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 148650 entries, 0 to 148649
Data columns (total 13 columns):
 #   Column            Non-Null Count   Dtype
---  ------            --------------   -----
 0   Id                148650 non-null  int64
 1   EmployeeName      148650 non-null  object
 2   JobTitle          148650 non-null  object
 3   BasePay           148045 non-null  float64
 4   OvertimePay       148650 non-null  float64
 5   OtherPay          148650 non-null  float64
 6   Benefits          112491 non-null  float64
 7   TotalPay          148650 non-null  float64
 8   TotalPayBenefits  148650 non-null  float64
 9   Year              148650 non-null  int64
 10  Notes             0 non-null       float64
 11  Agency            148650 non-null  object
 12  Status            38119 non-null   object
dtypes: float64(7), int64(2), object(4)
memory usage: 14.7+ MB

In [11]:
df.describe()

,Id,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes
count,148650.000000,148045.000000,148650.000000,148650.000000,112491.000000,148650.000000,148650.000000,148650.000000,0.0
mean,74325.500047,66325.448840,5066.059886,3648.767297,25007.893151,74770.333901,93695.075969,2012.522603,NaN
std,42911.703176,42764.635495,11454.380559,8056.601866,15402.215858,50516.196009,62792.497391,1.117526,NaN
min,1.000000,-166.010000,-0.010000,-7058.590000,-33.890000,-618.130000,-618.130000,2011.000000,NaN
25%,37163.250000,33588.200000,0.000000,0.000000,11535.395000,36169.955000,44073.337500,2012.000000,NaN
50%,74325.500000,65007.450000,0.000000,811.270000,28628.620000,71427.240000,92406.020000,2013.000000,NaN
75%,111487.750000,94691.050000,4658.175000,4236.065000,35566.855000,105842.960000,132877.992500,2014.000000,NaN
max,148654.000000,319275.010000,245131.880000,400184.250000,96570.660000,567595.430000,567595.430000,2014.000000,NaN

In [12]:
df['BasePay']

0         167411.18
1         155966.02
2         212739.13
3          77916.00
4         134401.60
            ...
148645         0.00
148646         0.00
148647         0.00
148648         0.00
148649         0.00
Name: BasePay, Length: 148650, dtype: float64

In [13]:
df['BasePay'].mean()

66325.4488404877

In [14]:
df['OvertimePay'].max()

245131.88

In [15]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['JobTitle']

24    CAPTAIN, FIRE SUPPRESSION
Name: JobTitle, dtype: object

In [16]:
df[df['EmployeeName'] == 'JOSEPH DRISCOLL']['TotalPayBenefits']

24    270324.91
Name: TotalPayBenefits, dtype: float64

In [17]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].max()]['EmployeeName']

0    NATHANIEL FORD
Name: EmployeeName, dtype: object

In [18]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].min()]['EmployeeName']

148649    Joe Lopez
Name: EmployeeName, dtype: object

In [19]:
df[df['TotalPayBenefits'] == df['TotalPayBenefits'].min()]

,Id,EmployeeName,JobTitle,BasePay,OvertimePay,OtherPay,Benefits,TotalPay,TotalPayBenefits,Year,Notes,Agency,Status
148649,148654,Joe Lopez,"Counselor, Log Cabin Ranch",0.0,0.0,-618.13,0.0,-618.13,-618.13,2014,NaN,San Francisco,PT

In [20]:
df['JobTitle'].nunique()

2158

In [21]:
df['JobTitle'].value_counts()[:5]

Transit Operator                7036
Special Nurse                   4389
Registered Nurse                3736
Public Svc Aide-Public Works    2518
Police Officer 3                2421
Name: JobTitle, dtype: int64

In [22]:
def chief(string):
  if 'chief' in (string.lower()):
    return True
  else:
    return False

In [23]:
chief('GENERAL MANAGER-METROPOLITAN TRANSIT AUTHORITY	')

False

In [24]:
(df['JobTitle'].apply(lambda x: chief(x))).sum()

627

In [25]:
df['ntitles'] = df['JobTitle'].apply(len)
df['ntitles']

0         46
1         31
2         31
3         36
4         44
          ..
148645    25
148646    27
148647     9
148648     9
148649    26
Name: ntitles, Length: 148650, dtype: int64

In [27]:
df[['ntitles','TotalPayBenefits']].corr()

                  ntitles  TotalPayBenefits
ntitles           1.00000          -0.03692
TotalPayBenefits -0.03692           1.00000